### ISSUE TITLE
Compilation errors on following instructions

### ISSUE THREAD

**Issue by abhi18av** [enricosada/fsharp-dotnet-cli-samples#9]
Hii @enricosada 

I'm looking forward to trying out a few projects with  `dotnet-core`  and `F#`, which led me to this repo. However when I run this `dotnet run arg1 arg2` or even `dotnet build` command after the `dotnet restore` command I get the following error

```sh
Project fsharp-1 (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
Compiling fsharp-1 for .NETCoreApp,Version=v1.1
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
/usr/share/dotnet/dotnet compile-fsc @/home/abhi18av/Desktop/fsharp-1/obj/Debug/netcoreapp1.1/dotnet-compile.rsp returned Exit Code 131

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.2334882


```

If it's a newbie question then, I apologize - It's only because I really am :smile:

**Comment by enricosada** [comment]
Hi @abhi18av i have seen this issue just now, sry for late reply.

The repository has moved. 

Now there a new repo and a wiki with all updated info is in https://github.com/dotnet/netcorecli-fsc/wiki

For example your issue is about https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview2.1
See workaround in the wiki page.

Or install the .NET Core 1.0 (LTS version, named `preview2`). see https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview2 about that
